# Generated by Django 4.2.1 on 2023-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_colorvarient_sizevarient_products_color_varient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvarient',
            name='color_varient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sizevarient',
            name='size_varient',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
